Repository GovTechSG/apex-signature-validator, pull requests merged in 2018-03, with the labels that each got.

#2 Minor version 0.25 Bump
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation, security

#3 Version 0.3.0 Initial release - JOSE Feature
  .gitignore
  CHANGELOG.md
  README.md
  assets/jose_jwe.png
  assets/jose_jws.png
  index.ejs
  package-lock.json
  package.json
  src/app.js
  src/controllers/mainController.js
  src/service/jwtService.js
Labels: documentation, enhancement

#4 Feature/state separation
  .gitignore
  CHANGELOG.md
  README.md
  assets/homepage.png
  assets/jose_jwe.png
  assets/jose_jwe_verified.png
  assets/jose_jws.png
  assets/jose_jws_verified.png
  index.ejs
  package-lock.json
  package.json
  src/app.js
  src/controllers/mainController.js
  src/controllers/navbarController.js
  src/css/style.css
  src/features/joseValidator.js
  src/features/paramsModal.js
  src/features/signatureValidator.js
  src/mainController.js
  src/service/config.js
  src/service/jwtService.js
  src/service/testService.js
  src/service/utiityService.js
  webpack.config.js
Labels: enhancement
